services:
  e2e:
    build: .
    image: bootcamp/ext-e2e:latest
    environment:
      - CI=true
    volumes:
      - ./:/app
      # Esta é a linha mais importante, que conserta o ambiente:
      - /app/node_modules
    working_dir: /app
    command: npm run test
    shm_size: 2gb